codecov:
  require_ci_to_pass: yes
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/test/**"
  - "lib/**/*_test.dart"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
